table dim_date
	lineageTag: d0e98e1f-69c7-4e68-85dc-37c79bf71831
	dataCategory: Time

	column date_key
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 67227b06-47d0-4041-b705-68de41662fe1
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: f4077503-5e11-46f4-9059-7d985b899a7d
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter_number
		dataType: int64
		formatString: 0
		lineageTag: 5c4ec7ff-7be4-49e1-802b-7852a75cfc3f
		summarizeBy: sum
		sourceColumn: quarter_number

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: d037af8d-c84b-4f7d-a270-8ac17a27eb80
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 20a98c76-0085-4e1e-aed0-e45d4811211a
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: cc38b089-0d23-431b-9b3b-ea19ce0ce092
		summarizeBy: none
		sourceColumn: year_month
		sortByColumn: month_start

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column month_start
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2c4b56c0-a7ae-4c1a-bebb-00ed5819a9da
		summarizeBy: none
		sourceColumn: month_start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Parquet.Document(
				        File.Contents(SourcePath & "\dim_date.parquet")
				    ),
				    Typed = Table.TransformColumnTypes(
				        Source,
				        {
				            {"date_key", type date},
				            {"year", Int64.Type},
				            {"quarter_number", Int64.Type},
				            {"month_number", Int64.Type},
				            {"month_name", type text},
				            {"year_month", type text},
				            {"month_start", type date}
				        }
				    )
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

